language: cpp
os:
- linux
compiler:
- gcc
sudo: required
services: docker
before_install:
- docker build -t ovilab/neuronify -f .docker/Dockerfile .
script:
- docker run ovilab/neuronify bash -c "/opt/qt57/bin/qmake neuronify.pro && make
  -j8"
branches:
  except:
    - appveyor
