language: cpp
os:
- linux
compiler:
- gcc
sudo: required
services: docker
notifications:
  slack:
    on_success: change
    on_failure: always
    secure: kuyFzncY4kcv2ZAyHg6jYL7ASfKMirXSTRr8OVsFBh6exTvItqkFmzcgxhke9Foqp2KJuKOSg8qf2pP2mpW/JznssDJLrcUxbCGakt3BYLXtuE3ZD+3SVwvjBPkBJncG5knEayMW0TCBWI+FZBnzH66RwP2iQRVGkXJX4skVOSM=
before_install:
- docker build -t ovilab/neuronify -f .docker/Dockerfile .
script:
- docker run ovilab/neuronify bash -c "/opt/qt57/bin/qmake neuronify.pro && make
  -j8"
